## Creating pandas series

In [1]:
import numpy as np
import pandas as pd

In [2]:
list1 = [1,2,3,4,5]
arr = np.array([10,20,30,40,50])
labels = ['a','b','c','d','e']
dict = {1:'priya' , 2: 'bala',3:'cricket',4: 'badminton', 5: 'gol-gappe'}

In [3]:
pd.Series(arr, index = labels)

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [4]:
pd.Series(dict)

1        priya
2         bala
3      cricket
4    badminton
5    gol-gappe
dtype: str

# Data Frames

In [5]:
# using a dictionary
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df1 = pd.DataFrame(data)
df1

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [6]:
#using list
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
cols = ["name","age","city","salary"]
df2 = pd.DataFrame(data_list, columns = cols)
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [7]:
df1["Salary"]

0    65000
1    70000
2    62000
3    85000
Name: Salary, dtype: int64

In [8]:
df2[["name", "age"]]

    name  age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

## creating a new column

In [9]:
df2["experience years"] = [1,2,3,4]
df2

    name  age      city  salary  experience years
0   John   28  New York   65000                 1
1   Anna   34     Paris   70000                 2
2  Peter   29    Berlin   62000                 3
3  Linda   42    London   85000                 4

### removing a column

In [10]:
df2.drop("experience years" , axis = 1)

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [11]:
df2

    name  age      city  salary  experience years
0   John   28  New York   65000                 1
1   Anna   34     Paris   70000                 2
2  Peter   29    Berlin   62000                 3
3  Linda   42    London   85000                 4

In [12]:
df2.drop("experience years" , axis = 1, inplace = True)

In [13]:
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

### selecting a row

In [14]:
df2.loc[[0,1]]

   name  age      city  salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

### selecting a subset

In [15]:
df2.loc[[2,3]] [["name","age"]]

    name  age
2  Peter   29
3  Linda   42

In [16]:
df2[(df2["age"] > 30) & (df2["city"] == "Paris")]

   name  age   city  salary
1  Anna   34  Paris   70000

# Missing Data

In [17]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [18]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [19]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [20]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

### remove missing data

In [21]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [22]:
df.dropna(thresh = 2)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [23]:
df.dropna(thresh = 3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [24]:
df.dropna(thresh = 4)

     A  B    C    D
0  1.0  1  1.0  1.0

### fill missing values

In [25]:
df.fillna("x")

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0    x
2    x  3  3.0    x
3  4.0  4    x    x
4  5.0  5    x  5.0

In [26]:
values = {'A':0,'B':100,"C":300,'D':400}
df.fillna(values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

# Merging , Joining , Concatenation

### merging

In [27]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [28]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [29]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [30]:
pd.merge(employees, salaries)

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [31]:
# better as no null values (AS ONLY COMMOM PART IS PRINTED.) Preffered as  null values are danger
pd.merge(employees, salaries, on = "employee_id", how = "inner")

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [32]:
pd.merge(employees, salaries, on = "employee_id", how = "outer")

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [33]:
pd.merge(employees, salaries, on = "employee_id", how = "left")

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [34]:
pd.merge(employees, salaries, on = "employee_id", how = "right")

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

### concatenation

In [35]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [36]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [37]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [38]:
pd.concat([df1,df2])
# pd.concat((df1,df2)) # axis = 0  by default

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [39]:
pd.concat((df1,df2), axis = 1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

### joining

In [40]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [41]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [42]:
df2

   score
2     85
3     90
4     75

In [43]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [44]:
df1.join(df2 ,  how = "inner")

      name  score
2      Bob     85
3  Charlie     90

In [45]:
df1.join(df2 ,  how = "outer")

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [46]:
df2.join(df1 ,  how = "outer")

   score     name
1    NaN    Alice
2   85.0      Bob
3   90.0  Charlie
4   75.0      NaN

In [47]:
df2.join(df1)

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN

# Group By Aggregation

In [48]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}

In [49]:
df1 = pd.DataFrame(data)
df1

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [50]:
# Group by Category and calculate the sum of Sales
category = df1.groupby("Category")
for x,y in category:
    print(x)
    print(y)

A
  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
2        A    S2    150        12 2023-01-03
4        A    S1    120         8 2023-01-05
6        A    S2    200        15 2023-01-07
B
  Category Store  Sales  Quantity       Date
1        B    S1    200        15 2023-01-02
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06
7        B    S1    300        25 2023-01-08

In [51]:
category = df1.groupby("Category")["Sales"].sum()
category

Category
A    570
B    930
Name: Sales, dtype: int64

In [52]:
# Group by Store and calculate the sum of Sales
store = df1.groupby("Store")
for x,y in store:
    print(x)
    print(y)

S1
  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
4        A    S1    120         8 2023-01-05
7        B    S1    300        25 2023-01-08
S2
  Category Store  Sales  Quantity       Date
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07

In [53]:
store = df1.groupby("Store")["Sales"].sum()
store

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [55]:
# Group by Category and Store together(MULTIPLE COLUMNS)
multiple = df1.groupby(["Category", "Store"])["Sales"].sum()
multiple

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

In [58]:
df1["Sales"].mean()

np.float64(187.5)

In [62]:
df1["Sales"].agg(["mean","median","max","min","count","std"])
# .agg not applicable for mode*

mean      187.500000
median    190.000000
max       300.000000
min       100.000000
count       8.000000
std        66.062741
Name: Sales, dtype: float64

# Pivot Tables and Cross Tab

In [63]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    251     39   John  January      Q1
1  2023-01-02       B   West    711     19   Mary  January      Q1
2  2023-01-03       C  North    117     43    Bob  January      Q1
3  2023-01-04       D  South    634     26  Alice  January      Q1
4  2023-01-05       A   East    650     33   John  January      Q1
5  2023-01-06       B   West    562     60   Mary  January      Q1
6  2023-01-07       C  North    926     10    Bob  January      Q1
7  2023-01-08       D  South    124     52  Alice  January      Q1
8  2023-01-09       A   East    925     47   John  January      Q1
9  2023-01-10       B   West    420     29   Mary  January      Q1
10 2023-01-11       C  North    441     89    Bob  January      Q1
11 2023-01-12       D  South    536     14  Alice  January      Q1
12 2023-01-13       A   East    730     86   John  January      Q1
13 2023-01-14       B   West    468     62   Mary  January      Q1
14 2023-01-15       C  North    967     60    Bob  January      Q1
15 2023-01-16       D  South    997     84  Alice  January      Q1
16 2023-01-17       A   East    565     14   John  January      Q1
17 2023-01-18       B   West    411     57   Mary  January      Q1
18 2023-01-19       C  North    867     16    Bob  January      Q1
19 2023-01-20       D  South    510     10  Alice  January      Q1

In [64]:
pd.pivot_table(df, values = "Units", index = "Region", columns = "Product")

Product     A     B     C     D
Region
East     43.8   NaN   NaN   NaN
North     NaN   NaN  43.6   NaN
South     NaN   NaN   NaN  37.2
West      NaN  45.4   NaN   NaN

In [71]:
pd.pivot_table(df, values = "Units", index = "Region", columns = "Product", aggfunc = "median")

Product     A     B     C     D
Region
East     39.0   NaN   NaN   NaN
North     NaN   NaN  43.0   NaN
South     NaN   NaN   NaN  26.0
West      NaN  57.0   NaN   NaN

In [72]:
newpivot = pd.pivot_table(df, values = ["Units", "Sales"], index = "Region", columns = "Product")
newpivot

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     624.2    NaN    NaN    NaN  43.8   NaN   NaN   NaN
North      NaN    NaN  663.6    NaN   NaN   NaN  43.6   NaN
South      NaN    NaN    NaN  560.2   NaN   NaN   NaN  37.2
West       NaN  514.4    NaN    NaN   NaN  45.4   NaN   NaN

In [73]:
pd.crosstab(df["Region"], df["Product"])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

In [77]:
pd.crosstab(df["Region"], df["Product"])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

# Operations

In [78]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [79]:
df1.shape

(5, 3)

In [80]:
df1.size

15

In [83]:
df1.columns

Index(['A', 'B', 'C'], dtype='str')

In [86]:
df1.count()
# this is a function *

A    5
B    5
C    5
dtype: int64

In [88]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [89]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [90]:
df1["B"] + 100

0    110
1    120
2    130
3    140
4    150
Name: B, dtype: int64

# DataFrames Applying Functions

In [91]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [97]:
def cube(x):
    # return x*x*x
      return x ** 3

In [99]:
df1["A"].apply(cube)

0      1
1      8
2     27
3     64
4    125
Name: A, dtype: int64

In [102]:
df1["A"].apply(lambda x : x ** 2)

0     1
1     4
2     9
3    16
4    25
Name: A, dtype: int64